spring:
  liquibase:
    change-log: classpath:/schema.xml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${embedded.postgresql.host}:${embedded.postgresql.port}/${embedded.postgresql.schema}
    password: ${embedded.postgresql.password}
    username: ${embedded.postgresql.user}
server:
  port: 8082
prefix-service:
  version: v2
logging:
  level:
    root:
      - INFO
springdoc:
  use-management-port: true
  show-actuator: true
management:
  server:
    port: 9090
  endpoints:
    jmx:
      exposure:
        include: openapi, swagger-ui
